version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Secretop
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      -  8080:8080